# Generated by Django 5.2.8 on 2025-11-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('numero_pokedex', models.PositiveIntegerField(unique=True, verbose_name='Número en Pokédex')),
                ('descripcion', models.TextField(help_text='Descripción del Pokémon')),
                ('tipo_primario', models.CharField(max_length=20)),
                ('tipo_secundario', models.CharField(blank=True, max_length=20, null=True)),
                ('ataque_1_nombre', models.CharField(max_length=50)),
                ('ataque_1_tipo', models.CharField(max_length=20)),
                ('ataque_1_poder', models.PositiveIntegerField(default=0)),
                ('ataque_1_precision', models.PositiveIntegerField(default=100)),
                ('ataque_2_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('ataque_2_tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('ataque_2_poder', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('ataque_2_precision', models.PositiveIntegerField(blank=True, default=100, null=True)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen del Pokémon', null=True, upload_to='pokemon_images/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pokémon',
                'verbose_name_plural': 'Pokémones',
                'ordering': ['numero_pokedex'],
            },
        ),
    ]
